import { StyleSheet } from "react-native";
import colors from "../theme/colors";
import Dimensions from "./dimensions.style";

const globalStyles = StyleSheet.create({
  // ================== Layout ==================
  screen: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  container: {
    padding: Dimensions.SIZE_L,
    borderRadius: Dimensions.SIZE_XS,
    backgroundColor: colors.background.primary,
  },
  // ================== Flex Layout ==================
  flex_row: { flexDirection: "row" },
  flex_col: { flexDirection: "column" },
  flex_none: { flex: undefined },
  flex_1: { flex: 1 },
  flex_grow: { flexGrow: 1 },
  flex_shrink: { flexShrink: 1 },
  flex_wrap: { flexWrap: "wrap" },
  flex_nowrap: { flexWrap: "nowrap" },
  flex_between: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  link_text: {
    textDecorationStyle: "dotted",
    textDecorationLine: "underline",
  },
  flex_95: { flex: 0.95 },
  flex_9: { flex: 0.9 },
  flex_8: { flex: 0.8 },
  flex_7: { flex: 0.7 },
  flex_6: { flex: 0.6 },
  flex_5: { flex: 0.5 },
  // Displays
  display_contents: { display: "contents" },
  display_flex: { display: "flex" },
  display_none: { display: "none" },
  //  Items
  items_end: { alignItems: "flex-end" },
  items_center: { alignItems: "center" },
  items_start: { alignItems: "flex-start" },
  items_baseline: { alignItems: "baseline" },
  items_stretch: { alignItems: "stretch" },
  // self
  self_center: { alignSelf: "center" },
  self_start: { alignSelf: "flex-start" },
  self_end: { alignSelf: "flex-end" },
  self_stretch: { alignSelf: "stretch" },
  self_baseline: { alignSelf: "baseline" },
  // Justify
  justify_end: { justifyContent: "flex-end" },
  justify_center: { justifyContent: "center" },
  justify_start: { justifyContent: "flex-start" },
  justify_even: { justifyContent: "space-evenly" },
  justify_around: { justifyContent: "space-around" },
  justify_between: { justifyContent: "space-between" },

  //elevation
  elevation_xs: { elevation: Dimensions.SIZE_XS },
  elevation_sm: { elevation: Dimensions.SIZE_SM },
  elevation_md: { elevation: Dimensions.SIZE_M },
  elevation_lg: { elevation: Dimensions.SIZE_L },
  elevation_xl: { elevation: Dimensions.SIZE_XL },

  // ================== Alignment ==================
  center: { justifyContent: "center", alignItems: "center" },
  center_row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  between: { justifyContent: "space-between" },
  around: { justifyContent: "space-around" },
  even: { justifyContent: "space-evenly" },
  start: { justifyContent: "flex-start" },
  end: { justifyContent: "flex-end" },
  top: { alignItems: "flex-start" },
  middle: { alignItems: "center" },
  bottom: { alignItems: "flex-end" },
  stretch: { alignItems: "stretch" },

  // ================== Positioning ==================
  absolute: { position: "absolute" },
  relative: { position: "relative" },

  top_0: { top: 0 },
  top_50: { top: "50%" },
  top_xs: { top: Dimensions.SIZE_XS },
  top_2xs: { top: Dimensions.SIZE_XS / 2 },

  left_0: { left: 0 },
  // ====== Right =====
  right_0: { right: 0 },
  right_xs: { right: Dimensions.SIZE_XS },
  right_sm: { right: Dimensions.SIZE_SM },
  right_md: { right: Dimensions.SIZE_M },
  right_lg: { right: Dimensions.SIZE_L },
  right_xl: { right: Dimensions.SIZE_XL },

  bottom_0: { bottom: 0 },
  bottom_full: { bottom: "100%" },
  _bottom_0: { bottom: Dimensions.SIZE_XS },

  // ================== Spacing ==================
  // Widths
  w_xs: { width: Dimensions.SIZE_XS },
  w_sm: { width: Dimensions.SIZE_SM },
  w_md: { width: Dimensions.SIZE_M },
  w_lg: { width: Dimensions.SIZE_L },
  w_xl: { width: Dimensions.SIZE_XL },
  w_auto: { width: "auto" },
  w_full_screen: { width: Dimensions.SCREEN_WIDTH },
  w_full: { width: "100%" },
  w_95: { width: "95%" },
  w_90: { width: "90%" },
  w_80: { width: "80%" },
  w_70: { width: "70%" },
  w_60: { width: "60%" },
  w_50: { width: "50%" },
  w_45: { width: "45%" },
  w_40: { width: "40%" },
  w_33: { width: "33.33%" },
  w_30: { width: "30%" },
  w_20: { width: "20%" },
  // min width
  min_w_10: { minWidth: "10%" },
  min_w_20: { minWidth: "20%" },
  min_w_30: { minWidth: "30%" },
  min_w_33: { minWidth: "33.33%" },
  min_w_45: { minWidth: "45%" },
  min_w_50: { minWidth: "50%" },
  min_w_55: { minWidth: "55%" },
  min_w_60: { minWidth: "60%" },
  min_w_65: { minWidth: "65%" },
  min_w_70: { minWidth: "70%" },
  min_w_75: { minWidth: "75%" },
  min_w_80: { minWidth: "80%" },
  min_w_85: { minWidth: "85%" },
  min_w_90: { minWidth: "90%" },
  min_w_95: { minWidth: "95%" },
  min_w_100: { minWidth: "100%" },
  // scree width
  ws_20: { width: Dimensions.SCREEN_WIDTH * 0.2 },
  ws_30: { width: Dimensions.SCREEN_WIDTH * 0.3 },
  ws_40: { width: Dimensions.SCREEN_WIDTH * 0.4 },
  ws_50: { width: Dimensions.SCREEN_WIDTH * 0.5 },
  ws_60: { width: Dimensions.SCREEN_WIDTH * 0.6 },
  ws_70: { width: Dimensions.SCREEN_WIDTH * 0.7 },
  ws_80: { width: Dimensions.SCREEN_WIDTH * 0.8 },
  ws_90: { width: Dimensions.SCREEN_WIDTH * 0.9 },
  ws_100: { width: Dimensions.SCREEN_WIDTH },
  // max width
  max_w_30: { maxWidth: "30%" },
  max_w_40: { maxWidth: "40%" },
  max_w_45: { maxWidth: "45%" },
  max_w_50: { maxWidth: "50%" },
  max_w_60: { maxWidth: "60%" },
  max_w_70: { maxWidth: "70%" },
  max_w_80: { maxWidth: "80%" },

  // heights
  h_xs: { height: Dimensions.SIZE_XS },
  h_sm: { height: Dimensions.SIZE_SM },
  h_md: { height: Dimensions.SIZE_M },
  h_lg: { height: Dimensions.SIZE_L },
  h_xl: { height: Dimensions.SIZE_XL },
  h_auto: { height: "auto" },
  h_full: { height: "100%" },
  h_60: { height: "60%" },
  h_70: { height: "70%" },
  h_80: { height: "80%" },
  h_input: { height: Dimensions.INPUT_HEIGHT },
  hs_100: { height: Dimensions.SCREEN_HEIGHT },
  hs_90: { height: Dimensions.SCREEN_HEIGHT * 0.9 },
  hs_80: { height: Dimensions.SCREEN_HEIGHT * 0.8 },
  hs_70: { height: Dimensions.SCREEN_HEIGHT * 0.7 },
  hs_60: { height: Dimensions.SCREEN_HEIGHT * 0.6 },
  hs_20: { height: Dimensions.SCREEN_HEIGHT * 0.2 },
  hs_10: { height: Dimensions.SCREEN_HEIGHT * 0.1 },
  hs_5: { height: Dimensions.SCREEN_HEIGHT * 0.05 },

  // max height
  max_h_10: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.1 },
  max_h_20: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.2 },
  max_h_30: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.3 },
  max_h_40: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.4 },
  max_h_50: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.5 },
  max_h_60: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.6 },
  max_h_70: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.7 },
  max_h_80: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.8 },
  max_h_90: { maxHeight: Dimensions.SCREEN_HEIGHT * 0.9 },
  max_h_100: { maxHeight: Dimensions.SCREEN_HEIGHT },

  // Border radius
  br_0: { borderRadius: 0 },
  br_xs: { borderRadius: Dimensions.SIZE_XS },
  br_sm: { borderRadius: Dimensions.SIZE_SM },
  br_md: { borderRadius: Dimensions.SIZE_M },
  br_lg: { borderRadius: Dimensions.SIZE_L },
  br_xl: { borderRadius: Dimensions.SIZE_XL },
  br_2xl: { borderRadius: Dimensions.SIZE_XL * 2 },
  br_3xl: { borderRadius: Dimensions.SIZE_XL * 3 },
  // Margins
  m_xs: { margin: Dimensions.SIZE_XS },
  m_sm: { margin: Dimensions.SIZE_SM },
  m_md: { margin: Dimensions.SIZE_M },
  m_lg: { margin: Dimensions.SIZE_L },
  m_xl: { margin: Dimensions.SIZE_XL },

  mt_0: { marginTop: 0 },
  mt_2xs: { marginTop: Dimensions.SIZE_XS / 2 },
  mt_xs: { marginTop: Dimensions.SIZE_XS },
  mt_sm: { marginTop: Dimensions.SIZE_SM },
  mt_md: { marginTop: Dimensions.SIZE_M },
  mt_lg: { marginTop: Dimensions.SIZE_L },
  mt_2lg: { marginTop: Dimensions.SIZE_LG },
  mt_xl: { marginTop: Dimensions.SIZE_XL },
  mt_2xl: { marginTop: Dimensions.SIZE_L * 2 },
  mt_status: { marginTop: Dimensions.STATUS_BAR_HEIGHT },

  _mt_xs: { marginTop: -Dimensions.SIZE_XS },
  _mt_sm: { marginTop: -Dimensions.SIZE_SM },
  _mt_md: { marginTop: -Dimensions.SIZE_M },
  _mt_lg: { marginTop: -Dimensions.SIZE_L },
  _mt_2lg: { marginTop: -Dimensions.SIZE_LG },
  _mt_xl: { marginTop: -Dimensions.SIZE_XL },
  _mt_2xl: { marginTop: -Dimensions.SIZE_L * 2 },

  mb_0: { marginBottom: 0 },
  mb_2xs: { marginBottom: Dimensions.SIZE_XS / 2 },
  mb_xs: { marginBottom: Dimensions.SIZE_XS },
  mb_sm: { marginBottom: Dimensions.SIZE_SM },
  mb_md: { marginBottom: Dimensions.SIZE_M },
  mb_lg: { marginBottom: Dimensions.SIZE_L },
  mb_xl: { marginBottom: Dimensions.SIZE_XL },
  mb_2xl: { marginBottom: Dimensions.SIZE_XL * 2 },

  gap_2xs: { gap: Dimensions.SIZE_XS / 2 },
  gap_xs: { gap: Dimensions.SIZE_XS },
  gap_sm: { gap: Dimensions.SIZE_SM },
  gap_md: { gap: Dimensions.SIZE_M },
  gap_lg: { gap: Dimensions.SIZE_L },
  gap_xl: { gap: Dimensions.SIZE_XL },
  gap_2xl: { gap: Dimensions.SIZE_XL * 2 },

  ml_xs: { marginLeft: Dimensions.SIZE_XS },
  ml_xs_up: { marginLeft: Dimensions.SIZE_XS + 2 },
  ml_sm_down: { marginLeft: Dimensions.SIZE_SM - 2 },
  ml_sm: { marginLeft: Dimensions.SIZE_SM },
  ml_md: { marginLeft: Dimensions.SIZE_M },
  ml_lg: { marginLeft: Dimensions.SIZE_L },
  ml_xl: { marginLeft: Dimensions.SIZE_XL },

  mr_xs: { marginRight: Dimensions.SIZE_XS },
  mr_sm: { marginRight: Dimensions.SIZE_SM },
  mr_md: { marginRight: Dimensions.SIZE_M },
  mr_lg: { marginRight: Dimensions.SIZE_L },
  mr_xl: { marginRight: Dimensions.SIZE_XL },

  mx_0: { marginHorizontal: 0 },
  mx_auto: { marginHorizontal: "auto" },
  mx_xs: { marginHorizontal: Dimensions.SIZE_XS },
  mx_sm: { marginHorizontal: Dimensions.SIZE_SM },
  mx_md: { marginHorizontal: Dimensions.SIZE_M },
  mx_lg: { marginHorizontal: Dimensions.SIZE_L },
  mx_xl: { marginHorizontal: Dimensions.SIZE_XL },
  mx_2xs: { marginHorizontal: Dimensions.SIZE_XS / 2 },

  my_0: { marginVertical: 0 },
  my_2xs: { marginVertical: Dimensions.SIZE_XS / 2 },
  my_xs: { marginVertical: Dimensions.SIZE_XS },
  my_sm: { marginVertical: Dimensions.SIZE_SM },
  my_md: { marginVertical: Dimensions.SIZE_M },
  my_lg: { marginVertical: Dimensions.SIZE_L },
  my_xl: { marginVertical: Dimensions.SIZE_XL },

  // Paddings
  p_0: { padding: 0 },
  p_2xs: { padding: Dimensions.SIZE_XS / 2 },
  p_xs: { padding: Dimensions.SIZE_XS },
  p_sm: { padding: Dimensions.SIZE_SM },
  p_md: { padding: Dimensions.SIZE_M },
  p_lg: { padding: Dimensions.SIZE_L },
  p_xl: { padding: Dimensions.SIZE_XL },
  p_2xl: { padding: Dimensions.SIZE_XL * 2 },

  pt_0: { paddingTop: 0 },
  pt_xs: { paddingTop: Dimensions.SIZE_XS },
  pt_sm: { paddingTop: Dimensions.SIZE_SM },
  pt_md: { paddingTop: Dimensions.SIZE_M },
  pt_lg: { paddingTop: Dimensions.SIZE_L },
  pt_xl: { paddingTop: Dimensions.SIZE_XL },
  pt_2xl: { paddingTop: Dimensions.SIZE_XL * 2 },
  pt_3xl: { paddingTop: Dimensions.SIZE_XL * 3 },
  pt_4xl: { paddingTop: Dimensions.SIZE_XL * 4 },
  pt_5xl: { paddingTop: Dimensions.SIZE_XL * 5 },
  pt_SafeArea: { paddingTop: Dimensions.STATUS_BAR_HEIGHT },

  pb_0: { paddingBottom: 0 },
  pb_xs: { paddingBottom: Dimensions.SIZE_XS },
  pb_sm: { paddingBottom: Dimensions.SIZE_SM },
  pb_md: { paddingBottom: Dimensions.SIZE_M },
  pb_lg: { paddingBottom: Dimensions.SIZE_L },
  pb_xl: { paddingBottom: Dimensions.SIZE_XL },

  pl_xs: { paddingLeft: Dimensions.SIZE_XS },
  pl_sm: { paddingLeft: Dimensions.SIZE_SM },
  pl_md: { paddingLeft: Dimensions.SIZE_M },
  pl_lg: { paddingLeft: Dimensions.SIZE_L },
  pl_xl: { paddingLeft: Dimensions.SIZE_XL },

  pr_xs: { paddingRight: Dimensions.SIZE_XS },
  pr_sm: { paddingRight: Dimensions.SIZE_SM },
  pr_md: { paddingRight: Dimensions.SIZE_M },
  pr_lg: { paddingRight: Dimensions.SIZE_L },
  pr_xl: { paddingRight: Dimensions.SIZE_XL },

  px_0: { paddingHorizontal: 0 },
  px_xs: { paddingHorizontal: Dimensions.SIZE_XS },
  px_sm: { paddingHorizontal: Dimensions.SIZE_SM },
  px_md: { paddingHorizontal: Dimensions.SIZE_M },
  px_lg: { paddingHorizontal: Dimensions.SIZE_L },
  px_xl: { paddingHorizontal: Dimensions.SIZE_XL },
  px_2xl: { paddingHorizontal: Dimensions.SIZE_XL * 2 },

  py_0: { paddingVertical: 0 },
  py_2xs: { paddingVertical: Dimensions.SIZE_XS / 2 },
  py_xs: { paddingVertical: Dimensions.SIZE_XS },
  py_sm: { paddingVertical: Dimensions.SIZE_SM },
  py_md: { paddingVertical: Dimensions.SIZE_M },
  py_lg: { paddingVertical: Dimensions.SIZE_L },
  py_xl: { paddingVertical: Dimensions.SIZE_XL },

  // ================== Typography ==================
  font_300: { fontWeight: "300" },
  font_400: { fontWeight: "400" },
  font_500: { fontWeight: "500" },
  font_600: { fontWeight: "600" },
  font_700: { fontWeight: "700" },
  font_800: { fontWeight: "800" },
  font_900: { fontWeight: "900" },

  text_center: { textAlign: "center" },
  text_right: { textAlign: "right" },
  text_left: { textAlign: "left" },
  uppercase: { textTransform: "uppercase" },
  capitalize: { textTransform: "capitalize" },

  text_xs: { fontSize: Dimensions.FONT_SIZE_XS },
  text_sm: { fontSize: Dimensions.FONT_SIZE_SM },
  text_md: { fontSize: Dimensions.FONT_SIZE_M },
  text_lg: { fontSize: Dimensions.FONT_SIZE_L },
  text_xl: { fontSize: Dimensions.FONT_SIZE_XL },

  line_height_xs: { lineHeight: Dimensions.FONT_SIZE_XS },
  line_height_sm: { lineHeight: Dimensions.FONT_SIZE_SM },
  line_height_md: { lineHeight: Dimensions.FONT_SIZE_M },
  line_height_lg: { lineHeight: Dimensions.FONT_SIZE_L },
  line_height_xl: { lineHeight: Dimensions.FONT_SIZE_XL },
  line_height_2xl: { lineHeight: Dimensions.FONT_SIZE_2XL },
  line_height_3xl: { lineHeight: Dimensions.FONT_SIZE_3XL },
  line_height_4xl: { lineHeight: Dimensions.FONT_SIZE_4XL },

  // ================== Colors & Backgrounds ==================
  bg_background: { backgroundColor: colors.background.primary },
  bg_secondary: { backgroundColor: colors.background.secondary },
  bg_tertiary: { backgroundColor: colors.background.tertiary },
  bg_green_light: { backgroundColor: colors.success.tertiary },
  bg_danger: { backgroundColor: colors.danger.primary },
  bg_transparent: { backgroundColor: "transparent" },
  bg_gray: { backgroundColor: colors.background.tertiary },
  bg_black: { backgroundColor: colors.black },
  bg_primary: { backgroundColor: colors.primary },
  bg_primary_light: { backgroundColor: colors.primary_light },
  bg_gray_2: { backgroundColor: colors.background.tertiary },
  bg_white: { backgroundColor: colors.text.inverted },
  bg_white_50: { backgroundColor: colors.background.tertiary },
  bg_white_30: { backgroundColor: colors.background.tertiary },

  text_white: { color: colors.text.inverted },
  text_primary: { color: colors.primary },
  text_secondary: { color: colors.secondary },
  text_tertiary: { color: colors.tertiary },
  text_danger: { color: colors.danger.primary },
  text_green: { color: colors.success.primary },
  text_default: { color: colors.text.default },

  // ================== Borders ==================
  border_none: { borderWidth: 0 },
  border_t_none: { borderTopWidth: 0 },
  border_b_none: { borderBottomWidth: 0 },
  border_l_none: { borderLeftWidth: 0 },
  border_r_none: { borderRightWidth: 0 },
  border: { borderWidth: 0.5, borderColor: colors.border.primary },
  border_t: { borderTopWidth: 0.5, borderColor: colors.border.primary },
  border_t_secondary: {
    borderTopWidth: 0.5,
    borderColor: colors.border.secondary,
  },
  border_b: { borderBottomWidth: 0.5, borderColor: colors.border.primary },
  border_l: { borderLeftWidth: 0.5, borderColor: colors.border.primary },
  border_r: { borderRightWidth: 0.5, borderColor: colors.border.primary },
  border_secondary: { borderWidth: 0.5, borderColor: colors.border.primary },
  border_tertiary: { borderWidth: 0.5, borderColor: colors.text.tertiary },

  border_light: { borderWidth: 0.5, borderColor: colors.border.primary },
  border_default: { borderWidth: 1, borderColor: colors.text.default },
  border_primary: { borderWidth: 0.5, borderColor: colors.primary },
  border_black: { borderWidth: 0.5, borderColor: colors.black },
  border_darkSilver: { borderWidth: 0.5, borderColor: colors.border.primary },
  border_dotted: {
    borderStyle: "dotted",
  },
  border_dashed: {
    borderStyle: "dashed",
  },

  stroke_white: { borderColor: colors.text.default },

  bg_black_10: {
    backgroundColor: colors.overlays.black_10,
  },
  bg_black_50: {
    backgroundColor: colors.overlays.black_50,
  },
  bg_black_80: {
    backgroundColor: colors.overlays.black_80,
  },

  rounded_xs: { borderRadius: Dimensions.SIZE_XS },
  rounded_sm: { borderRadius: Dimensions.SIZE_SM },
  rounded_md: { borderRadius: Dimensions.SIZE_M },
  rounded_lg: { borderRadius: Dimensions.SIZE_L },
  rounded_xl: { borderRadius: Dimensions.SIZE_XL },
  rounded_2xl: { borderRadius: Dimensions.SIZE_XL * 2 },
  rounded_3xl: { borderRadius: Dimensions.SIZE_XL * 3 },
  rounded_4xl: { borderRadius: Dimensions.SIZE_XL * 4 },
  rounded_5xl: { borderRadius: Dimensions.SIZE_XL * 5 },

  rounded_t_none: { borderTopLeftRadius: 0, borderTopRightRadius: 0 },
  rounded_t_xs: {
    borderTopLeftRadius: Dimensions.SIZE_XS,
    borderTopRightRadius: Dimensions.SIZE_XS,
  },
  rounded_t_sm: {
    borderTopLeftRadius: Dimensions.SIZE_SM,
    borderTopRightRadius: Dimensions.SIZE_SM,
  },
  rounded_t_md: {
    borderTopLeftRadius: Dimensions.SIZE_M,
    borderTopRightRadius: Dimensions.SIZE_M,
  },

  rounded_none: { borderRadius: 0 },
  rounded_l_none: { borderTopLeftRadius: 0, borderBottomLeftRadius: 0 },
  rounded_r_none: { borderTopRightRadius: 0, borderBottomRightRadius: 0 },

  rounded_b_none: { borderBottomLeftRadius: 0, borderBottomRightRadius: 0 },
  rounded_b_sm: { borderBottomLeftRadius: Dimensions.SIZE_SM, borderBottomRightRadius: Dimensions.SIZE_SM },
  rounded_b_md: { borderBottomLeftRadius: Dimensions.SIZE_M, borderBottomRightRadius: Dimensions.SIZE_M },
  rounded_b_lg: { borderBottomLeftRadius: Dimensions.SIZE_L, borderBottomRightRadius: Dimensions.SIZE_L },
  rounded_b_xl: { borderBottomLeftRadius: Dimensions.SIZE_XL, borderBottomRightRadius: Dimensions.SIZE_XL },

  // ================== Effects ==================
  shadow: {
    shadowOpacity: 0.3,
    shadowColor: colors.black,
    shadowRadius: Dimensions.SIZE_XS,
    elevation: Dimensions.SIZE_XS / 2,
    shadowOffset: { width: 0, height: 0 },
  },
  shadow_M: {
    shadowOpacity: 1,
    shadowColor: colors.black,
    shadowRadius: Dimensions.SIZE_XS,
    elevation: Dimensions.SIZE_XS / 2,
    shadowOffset: { width: 0, height: 0 },
  },
  opacity_025: { opacity: 0.025 },
  opacity_05: { opacity: 0.05 },
  opacity_10: { opacity: 0.1 },
  opacity_20: { opacity: 0.2 },
  opacity_30: { opacity: 0.3 },
  opacity_50: { opacity: 0.5 },
  opacity_80: { opacity: 0.8 },
  opacity_100: { opacity: 1 },

  // ================== Transforms ==================
  translateY_5xs: { transform: [{ translateY: Dimensions.SIZE_XS / 5 }] },
  translateY_2xs: { transform: [{ translateY: Dimensions.SIZE_XS / 2 }] },
  translateY_xs: { transform: [{ translateY: Dimensions.SIZE_XS }] },
  translateY_sm: { transform: [{ translateY: Dimensions.SIZE_SM }] },
  translateY_md: { transform: [{ translateY: Dimensions.SIZE_M }] },
  translateY_lg: { transform: [{ translateY: Dimensions.SIZE_L }] },

  _translateY_2xs: { transform: [{ translateY: -Dimensions.SIZE_XS / 2 }] },
  _translateY_xs: { transform: [{ translateY: -Dimensions.SIZE_XS }] },
  _translateY_sm: { transform: [{ translateY: -Dimensions.SIZE_SM }] },
  _translateY_md: { transform: [{ translateY: -Dimensions.SIZE_M }] },
  _translateY_lg: { transform: [{ translateY: -Dimensions.SIZE_L }] },
  _translateY_2lg: { transform: [{ translateY: -Dimensions.SIZE_LG }] },
  _translateY_xl: { transform: [{ translateY: -Dimensions.SIZE_XL }] },

  translateX_xs: { transform: [{ translateX: Dimensions.SIZE_XS }] },
  translateX_sm: { transform: [{ translateX: Dimensions.SIZE_SM }] },
  translateX_md: { transform: [{ translateX: Dimensions.SIZE_M }] },
  translateX_lg: { transform: [{ translateX: Dimensions.SIZE_L }] },

  _translateX_xs: { transform: [{ translateX: -Dimensions.SIZE_XS }] },
  _translateX_sm: { transform: [{ translateX: -Dimensions.SIZE_SM }] },
  _translateX_md: { transform: [{ translateX: -Dimensions.SIZE_M }] },
  _translateX_lg: { transform: [{ translateX: -Dimensions.SIZE_L }] },
  _translateX_2lg: { transform: [{ translateX: -Dimensions.SIZE_LG }] },
  _translateX_xl: { transform: [{ translateX: -Dimensions.SIZE_XL }] },

  rotate_90: { transform: [{ rotate: "90deg" }] },
  rotate_180: { transform: [{ rotate: "180deg" }] },
  rotate_270: { transform: [{ rotate: "270deg" }] },

  _rotate_90: { transform: [{ rotate: "-90deg" }] },
  _rotate_180: { transform: [{ rotate: "-180deg" }] },
  _rotate_270: { transform: [{ rotate: "-270deg" }] },

  // ================== Components ==================
  z_index_xs: { zIndex: 4 },
  z_index_sm: { zIndex: 8 },
  z_index_lg: { zIndex: 16 },
  // ================== Utilities ==================
  overflow_hidden: { overflow: "hidden" },
  lineThrough: { textDecorationLine: "line-through" },
  error: {
    textAlign: "center",
    color: colors.danger.primary,
    marginBottom: Dimensions.SIZE_L,
  },
  absoluteBottom: {
    width: "100%",
    position: "absolute",
    zIndex: 50,
    bottom: 0,
    left: 0,
    right: 0,
  },
});

export default globalStyles;
